package testCases;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;

import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.WebDriver;
import org.testng.Assert;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;

import pageObjects.DataNexusConnection;
import pageObjects.DataNexusMonitoring;
import pageObjects.DataNexusDataModel;
import pageObjects.DataNexusIngestionPipeline;
import pageObjects.DataNexusOrchestrator;
import pageObjects.DataNexusTransformationV2;
//import pageObjects.SharpInsightsTemporary;
import pageObjects.dataNexusHome;
import pageObjects.landingPage;
import pageObjects.loginPage;
import pageObjects.workspaceList;
import testBase.baseClass;
public class Regression_Testing_Script extends baseClass {
loginPage login;// Declare here
landingPage landing ;
workspaceList wslist;
DataNexusConnection conn;
DataNexusTransformationV2 v2;
DataNexusOrchestrator orch=new DataNexusOrchestrator(getDriver());
String IngestionPipelineName;
String TranformationPipelineName;
 String OrchestratorName = orch.orchestratorName;
 String ConnectionName;
@BeforeMethod
public void setupTestData() {
	login = new loginPage(getDriver()); // initialize after driver ready
	landing= new landingPage(getDriver());
	wslist = new workspaceList(getDriver());
	conn = new DataNexusConnection(getDriver());
	orch = new DataNexusOrchestrator(getDriver());
	v2= new DataNexusTransformationV2(getDriver());
	
}
	
	@Test(priority=1)
	public void loginSetup() throws IOException, InterruptedException {
		checkRunFlag("loginSetup");
		FileReader file = new FileReader("./src//test//resources//config.properties");
		p=new Properties();
		p.load(file);
		login = new loginPage(getDriver());
		SoftAssert softAssert = new SoftAssert();
		login.clickLogin();
		login.isObjectExist(login.blankField_Message);
		login.messageClose();
		login.isObjectExist(login.fieldRequire_Message);
		//Thread.sleep(5000);
		login.enterUsername("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
		login.enterPassword("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
		//Thread.sleep(2000);
		login.isObjectExist(login.maxlength);
		login.clearTextbox(login.username_textbox);
		login.clearTextbox(login.password_textbox);
		login.enterUsername("123@polestarllp.com");
		login.enterPassword("123");
		login.clickLogin();
	    //Thread.sleep(2000);
		//String userNotExistMsg=login.getLoginMessage();
		//softAssert.assertEquals(userNotExistMsg, "This user doesn't exists");
		//login.isObjectExist(login.userNotExist_Message),1);
		//login.messageClose();
		//Thread.sleep(5000);
		login.username_textbox.clear();
		login.password_textbox.clear();
		login.enterUsername("ankit@polestarllp.com");
		login.enterPassword("123");
		login.clickLogin();
		//String invalidUserMsg=login.getLoginMessage();
		//softAssert.assertEquals(invalidUserMsg, "Invalid credentials");
		//login.isObjectExist(login.invalidCredentials_Message);
		//login.messageClose();
		//Thread.sleep(5000);
		//Assert.fail();
		login.clearTextbox(login.username_textbox);
		login.clearTextbox(login.password_textbox);
		login.enterUsername("ankit@polestarllp.com");
		login.enterPassword("ankit@123");
		login.clickLogin();
		Thread.sleep(2000);
		String successLoginMessage=login.getLoginMessage();
		login.compareStrings(successLoginMessage, "Logged In Successfully.","Successful Login message");
	}
	
	@Test(dependsOnMethods = {"loginSetup"},priority=2)
	public void dataNexusHomePageNavigation() {
		checkRunFlag("LandingPage");
		landing.dataNexusClick();
	}
	@Test(dependsOnMethods = {"dataNexusHomePageNavigation"})
	public void dataNexus() throws InterruptedException, IOException {
		checkRunFlag("DataNexus");
		wslist.searchBox("CICD Updated");
		wslist.clickWorkSpace("CICD Updated");
		login.isHeaderPresent("h5", "Home");
		
	}
	@Test(priority=3)
	public void dataNexusHome() throws InterruptedException, IOException {
		dataNexusHome home = new dataNexusHome(getDriver());
		checkRunFlag("DataNexusHome");
		login.extendedWait.until(ExpectedConditions.visibilityOf(home.totalPipelines));
		login.isHeaderPresent("h5", "Home");
		home.searchBox(home.firstPipeline.getText());
		login.isObjectExist(home.firstPipeline);
		login.isValidDateFormat(home.createdDate.getText());
		home.clickActive();
		home.clickInctive();
		home.clickScheduled();
		login.isObjectExist(home.totalPipelines);
		login.isObjectExist(home.totalFailedTrigger);
		login.isObjectExist(home.totalSuccessTrigger);
		
	}
	@Test(priority=4)
	public void dataNexusConnection() throws InterruptedException, IOException {
		checkRunFlag("DataNexusConnection");
		conn =new DataNexusConnection(getDriver()) ;
		login.clickSideNavigationModule("Connections");
		login.isHeaderPresent("h5","Connections");
		String ConnectionName=conn.connectionname;
		//int initalcount=login.isPageInititiorAddedAfterCreation();
		login.clickCreateNew();
		//conn.clickConnectionType("Database");
		login.isHeaderPresent("span","Connections");
		conn.setConnectionName(ConnectionName);
		conn.clickFirstConnection();
		login.clickReset();
		login.isTextPresentAt(conn.connectionNameTextbox, "");
		login.textClick("div", "Database");
		conn.newConnectionSearchbox("ms server");
		conn.setConnectionName(ConnectionName);
		conn.clickFirstConnection();
		login.clickNext();
		conn.setDatabase("AdventureWorks2022");
		conn.setPassword("sql@1234");
		conn.setUserName("sqladmin");
		conn.setServer("psslp-genai.database.windows.net");
		conn.setPort("1433");
		login.testConnection();
		login.isObjectExist(conn.connectionTestSuccessMsg);
		login.clickSubmitButton();
		login.isObjectExist(conn.connectionAddedMsg);
		login.isHeaderPresent("h5","Connections");
		login.enterInSearchbox(ConnectionName);
		Thread.sleep(1000);
		login.isDataPresentInColumn("Connection Name", ConnectionName);
		login.isDataPresentInColumn("Source Type", "Mssql");
		login.isDataPresentInColumn("Created By", "Ankit Rana");
		login.isDataPresentInColumn("Created Date", login.todayDate);
		login.clickEdit();
		login.clearTextbox(conn.connectionNameTextbox);
		login.isObjectExist(conn.mandatoryConnectionName);
		login.testConnection();
		login.isObjectExist(conn.mandatoryConnectionMessage);
		conn.setConnectionName(ConnectionName);
		conn.setPort("143");
		login.testConnection();
		login.isObjectExist(conn.invalidCredentials_Message);
		conn.setPort("1433");
		login.testConnection();
		login.isObjectExist(conn.connectionTestSuccessMsg);
		login.clearTextbox(conn.serverTextbox);
		login.testConnection();
		login.isObjectExist(conn.invalidCredentials_Message);
		conn.setServer("psslp-genai.database.windows.net");
		login.testConnection();
		login.isObjectExist(conn.connectionTestSuccessMsg);
		login.clickSubmitButton();
		login.isObjectExist(conn.connectionUpdatedMsg);
		Thread.sleep(1000);
		login.clickCreateNew();
		String conn2="Test_Connection"+login.todayDate;
		//Assert.assertEquals(login.isPageInititiorAddedAfterCreation(), initalcount+1);
		login.isHeaderPresent("span","Connections");
		login.textClick("div", "Database");
		conn.newConnectionSearchbox("PostgreSQL");
		conn.setConnectionName(ConnectionName);
		conn.clickFirstConnection();
		login.clickNext();
		login.enterInTextbox("Host Name","platform-dev.postgres.database.azure.com");
		login.enterInTextbox("Port","5432");
		login.enterInTextbox("Database","oneplatform_db");
		login.enterInTextbox("User","dev");
		login.enterInTextbox("Password","Pole@4321");
		login.testConnection();
		login.isSuccessMessagePresent(conn.connectionTestSuccessMsg);
		login.clickSubmitButton();
		login.isSuccessMessagePresent(conn.duplicateNameMsg);
		conn.setConnectionName(conn2);
		login.testConnection();
		login.isSuccessMessagePresent(conn.connectionTestSuccessMsg);
		login.clickSubmitButton();
		login.isSuccessMessagePresent(conn.postgreMsg);
		login.isHeaderPresent("h5","Connections");
		login.enterInSearchbox(conn2);
		login.clickEdit();
		conn.clickEditConnectionType();
		conn.newConnectionSearchbox("SFTP");
		conn.clickFirstConnection();
		login.clickNext();
		login.enterInTextbox("Server","4.247.183.76");
		login.enterInTextbox("SSH Host Key","4.247.183.76");
		login.standardDropdownElement("Authentication Kind","Basic");
		login.enterInTextbox("Username","sftpuser");
		login.enterInTextbox("Password","Pole@sftp");
		login.testConnection();
		login.isObjectExist(conn.connectionTestSuccessMsg);
		login.clickSubmitButton();
		login.isObjectExist(conn.connectionUpdatedMsg);
		login.enterInSearchbox(conn2);
		login.clickDelete();
	}@Test(priority=5)
	public void dataNexusIngestionPipeline() throws InterruptedException, IOException {
		DataNexusIngestionPipeline igp = new DataNexusIngestionPipeline(getDriver());
		checkRunFlag("DataNexusIngestionPipeline");
		igp.clickSideNavigationModule("Ingestion Pipeline");
		igp.isHeaderPresent("h5","Ingestion Pipelines");
		login.clickCreateNew();
		igp.isHeaderPresent("span", "Create New");
		igp.enterPipelineName(igp.iGPipelineName);
		igp.clearTextbox(igp.pipelineName);
		igp.clickSpanText("Save Pipeline");
		login.isObjectExist(igp.mandatoryPipelineNameMsg);
		igp.isObjectExist(igp.blankPipelineMsg);
		igp.selectLakehouseName("Dev_Ingestion");
		igp.selectDatalkeName("BDS_SAMPLE_DATA");
		igp.selectSource(conn.connectionname);
		igp.selectSchema("dbo");
		igp.clickCheckBox("ADDUsers");
		igp.clickCheckBox("addValues");
		igp.clickCheckBox("AWBuildVersion");
		igp.selectLoadType("addValues", "Full Load");
		igp.selectLoadType("ADDUsers", "Incremental Load");
		igp.selectLoadTypeColumn("ADDUsers", "user_name");
		igp.selectLoadTypeCondition("ADDUsers", "Equal To");
		igp.selectLoadTypeIncValue("ADDUsers", "Ankit");
		igp.enterPipelineName(igp.iGPipelineName);
		igp.clickSpanText("Save Pipeline");
		login.isObjectExist(igp.columnSelectionMsg);
		igp.selectCustomQuery("AWBuildVersion");
		igp.enterCustomQuery("AWBuildVersion", "SELECT SystemInformationID, Database Version, VersionDate, ModifiedDate FROM dbo.AWBuildVersion");
		login.clickSaveButton();
		igp.columnSelector("ADDUsers");
		login.clickSaveButton();
		igp.columnSelector("addValues");
		login.clickSaveButton();
		igp.clickViewQueryBody("ADDUsers");
		login.isHeaderPresent("h3", "Preview Query");
		igp.clickCloseButton();
		igp.clickViewQueryBody("addValues");
		login.isObjectExist(igp.mandatoryColumnSelectionMsg);
		igp.clickSpanText("Save Pipeline");
		igp.isObjectExist(igp.pipelineCreatedMsg);
		login.enterInSearchbox(igp.iGPipelineName);
		login.isTextPresentInColumn("Pipeline Name", igp.iGPipelineName);
		login.isTextPresentInColumn("Source Connection Name", conn.connectionname);
		login.isTextPresentInColumn("Created By", "Ankit Rana");
		login.isTextPresentInColumn("Created Date", login.todayDate);
		login.clickSpanText(igp.iGPipelineName);
		login.isHeaderPresent("span", "Preview");
		login.clickSpanText("Ingestion Pipelines");
		login.clickYesButton();
		login.enterInSearchbox(igp.iGPipelineName);
		login.clickEdit();
		igp.clickCheckBox("Customers");
		igp.clickSpanText("Update Pipeline");
		igp.isObjectExist(igp.pipelineupdatedMsg);
		igp.clickSortingButton("Pipeline Name");
		igp.sortingValidation("Pipeline Name", "Ascending");
		igp.isHeaderPresent("span", "Create New");
		igp.enterPipelineName(igp.iGPipelineName);
		igp.clearTextbox(igp.pipelineName);
		igp.selectLakehouseName("Dev_Ingestion");
		igp.selectDatalkeName("BDS_SAMPLE_DATA");
		igp.selectSource(conn.connectionname);
		igp.selectSchema("dbo");
		igp.clickCheckBox("addValues");
		igp.selectLoadType("addValues", "Full Load");
		igp.columnSelector("addValues");
		login.clickSaveButton();
		igp.duplicatePipelineMsg(igp.iGPipelineName);
		String nPName="Test"+login.todayDate;
		igp.enterPipelineName(nPName);
		login.clickSaveButton();
		igp.isObjectExist(igp.pipelineCreatedMsg);
		login.enterInSearchbox(nPName);
		login.clickDelete();
		login.clickSpanText("Yes");
		login.isObjectExist(igp.deletePipelineMsg);
		
	}@Test(priority=7)
	public void dataNeuxsTransformationPipeline() throws Exception {
		checkRunFlag("DataNexusTransformationPipeline");
		TranformationPipelineName=v2.TransformationPipelineV2Name;
		login.clickSideNavigationModule("Transformation Pipeline v2");
		login.isHeaderPresent("h5", "Transformation Pipeline");
		login.clickSpanText("Create New");
		login.isDialogHeaderPresent("div", "Create New Transformation Pipeline");
		login.clickSpanText("Create & Proceed");
		v2.isSuccessMessagePresent(v2.mandatoryPipelineName);
		v2.enterPipelineName(TranformationPipelineName);
		v2.enterPipelineDescription("Automation Testing");
		login.clickSpanText("Create & Proceed");	
		//v2.openTransformationPannel();
		v2.selectSourceDataLake();
		login.isDialogHeaderPresent("div", "Configure Delta Lake Source");
		login.standardDropdownElement("Select Lakehouse", "lak1");
		login.standardDropdownElement("Select Lakehouse Type", "Tables");
		Thread.sleep(15000);
		login.typeAheadWebElement("Source Table", "customertestscd2");
		login.clickSpanText("Proceed");
		Thread.sleep(8000);
		v2.waitForPageLoad(v2.getPipelineNode("customertestscd2"));
		//v2.getPipelineNode("customertestscd2");
		//login.waitForPageLoad(v2.getPipelineNode("customertestscd2"));
		v2.clickZoomOutButton();
		//v2.clickZoomOutButton();
		//v2.clickZoomOutButton();
		//v2.selectSourceCustomScript();
		//login.isObjectExist(v2.pipelineNode);
		v2.addTargetDataLake();
		login.isDialogHeaderPresent("div", "Select Target Type");
		v2.clicksourceSelectionModel();
		login.isDialogHeaderPresent("div", "Configure Delta Lake Target");
		login.standardDropdownElement("Select Lakehouse", "lak1");
		login.standardDropdownElement("Select Lakehouse Type", "Tables");
		login.typeAheadWebElement("Target Table", "customertargetdim");
		login.clickSpanText("Proceed");
		login.waitForPageLoad(v2.getPipelineNode("customertargetdim"));
		v2.connectSourceTarget("customertestscd2", "customertargetdim");
		v2.clickSpanText("Save");
		login.isObjectExist(v2.pipelinesaved);
		login.doubleClick(v2.getPipelineNode("customertargetdim"), "customertargetdim");
		login.isDialogHeaderPresent("h2", "Target Configuration: Target_Operation");
		login.textClick("div", "Column Mapping");
		login.clickSpanText("Auto Map");
		v2.selectTransformationOutput("incremental_id");
		v2.targetConfigurationCloseButton();
		v2.clickSpanText("Save");
		//v2.deleteCanvas("Target_Operation - customertargetdim");
		//v2.deleteCanvas("customertestscd2");
		login.clickSpanText("Deploy");
		login.isObjectExist(v2.deployMessage);
		v2.searchbox(TranformationPipelineName);
		login.isDataPresentInColumn("Pipeline Name", TranformationPipelineName);
		login.isDataPresentInColumn("Description", "Automation Testing");
		login.isDataPresentInColumn("Created Date", login.todayDate);
		login.isDataPresentInColumn("Current Version", "Version 1");
		login.clickEdit();
		login.isObjectExist(v2.pipelineEditMsg);
		login.clickSpanText("Make a copy");
		login.isSuccessMessagePresent(v2.copeCreatedMsg);
		v2.deleteCanvas("Target_Operation - customertargetdim");
		v2.deleteCanvas("customertestscd2");
		//v2.openTransformationPannel();
		v2.selectSourceDataLake();
		login.isDialogHeaderPresent("div", "Configure Delta Lake Source");
		login.standardDropdownElement("Select Lakehouse", "lak1");
		login.standardDropdownElement("Select Lakehouse Type", "Tables");
		Thread.sleep(15000);
		login.typeAheadWebElement("Source Table", "1kimport");
		login.clickSpanText("Proceed");
		login.waitForPageLoad(v2.getPipelineNode("1kimport"));
		v2.clickZoomOutButton();
		v2.selectSourceDataLake();
		login.isDialogHeaderPresent("div", "Configure Delta Lake Source");
		login.standardDropdownElement("Select Lakehouse", "lak1");
		login.standardDropdownElement("Select Lakehouse Type", "Tables");
		login.typeAheadWebElement("Source Table", "1k_sample");
		login.clickSpanText("Proceed");
		login.waitForPageLoad(v2.getPipelineNode("1k_sample"));
		v2.clickZoomOutButton();
		v2.tranfomrationInputSearchbox("Join");
		v2.drangNDropInputType();
		v2.clickZoomOutButton();
		v2.connectSourceTarget("1kimport", "join");
		Thread.sleep(3000);
		v2.connectSourceTarget("1k_sample", "join");
		login.doubleClick(v2.getPipelineNode("join"), "Join");
		v2.isDialogHeaderPresent("h2", "Join Configuration");
		v2.clickSpanText("Apply Configuration");
		v2.isSuccessMessagePresent(v2.joinDuplicateColumnMsg);
		v2.clickSpanText("Add Join Condition");
		v2.selectJoinFrom("id");
		v2.selectJoinTo("id");
		v2.textClick("div", "Output Columns");
		v2.clickSpanText("Show Duplicates Only (6)");
		v2.clickDuplicateSlectAll("Source_2");
		v2.clickSpanText("Apply Configuration");
		v2.isSuccessMessagePresent(v2.saveJoinConfigMsg);
		v2.dialogCloseButton("h2", "Join Configuration");
		v2.tranfomrationInputSearchbox("Trim");
		v2.drangNDropInputType();
		v2.clickZoomOutButton();
		v2.connectSourceTarget("join", "trim");
		login.doubleClick(v2.getPipelineNode("trim"), "Trim");
		v2.isDialogHeaderPresent("h2", "Trim Configuration");
		v2.clickRadioButton("RTrim");
		v2.clickSpanText("Apply Configuration");
		v2.isSuccessMessagePresent(v2.saveTrimConfigMsg);
		v2.dialogCloseButton("h2", "Trim Configuration");
		v2.tranfomrationInputSearchbox("Data Quality Rules");
		v2.drangNDropInputType();
		v2.clickZoomOutButton();
		v2.connectSourceTarget("trim", "data_quality_rules");
		login.doubleClick(v2.getPipelineNode("data_quality_rules"), "Data Quality Rules");
		v2.isDialogHeaderPresent("h2", "Data Quality Rules Configuration");
		v2.selectDataQualityRuleType("Check Not Null");
		v2.clickSpanText("Add Rule");
		v2.selectDataQualityRuleColumn("id");
		v2.enterDataQualityRejectionRemark("Null not allowed");
		v2.clickSpanText("Apply Configuration");
		v2.isSuccessMessagePresent(v2.dataQualityConfigSaveMsg);
		v2.dialogCloseButton("h2", "Data Quality Rules Configuration");
		v2.tranfomrationInputSearchbox("Cast Data Type");
		v2.drangNDropInputType();
		v2.clickZoomOutButton();
		v2.connectSourceTarget("data_quality_rules", "cast_data_type");
		login.doubleClick(v2.getPipelineNode("cast_data_type"), "Cast Data type");
		v2.isDialogHeaderPresent("h2", "Cast Data Type Configuration");
		v2.enterCastDatatypeSearchColumn("quantity");
		v2.selectNewDataType("quantity", "Double");
		v2.clickSpanText("Apply Configuration");
		v2.isSuccessMessagePresent(v2.castDataConfigAppliedMsg);
		v2.dialogCloseButton("h2", "Cast Data Type Configuration");
		v2.tranfomrationInputSearchbox("Drop Columns");
		v2.drangNDropInputType();
		v2.clickZoomOutButton();
		v2.connectSourceTarget("cast_data_type", "drop_columns");
		login.doubleClick(v2.getPipelineNode("drop_columns"), "Drop Columns");
		v2.isDialogHeaderPresent("h2", "Drop Columns Configuration");
		v2.enterCastDatatypeSearchColumn("priority");
		login.clickCheckBox("priority");
		v2.clickSpanText("Apply Configuration");
		v2.isObjectExist(v2.dropCOlumnConfigSaveMsg);
		v2.dialogCloseButton("h2", "Drop Columns Configuration");
		v2.tranfomrationInputSearchbox("Drop duplicates");
		v2.drangNDropInputType();
		v2.clickZoomOutButton();
		v2.connectSourceTarget("drop_columns", "drop_duplicates");
		login.doubleClick(v2.getPipelineNode("drop_duplicates"), "Drop Duplicates");
		login.isDialogHeaderPresent("h2", "Drop Duplicates Configuration");
		login.clickSelectAllCheckbox();
		login.clickSpanText("Apply Configuration");
		login.isObjectExist(v2.removeDuplicateMsg);
		v2.dialogCloseButton("h2","Drop Duplicates Configuration");
		v2.addTargetDataLake();
		login.isDialogHeaderPresent("div", "Select Target Type");
		v2.clicksourceSelectionModel();
		login.isDialogHeaderPresent("div", "Configure Delta Lake Target");
		login.standardDropdownElement("Select Lakehouse", "lak1");
		login.standardDropdownElement("Select Lakehouse Type", "Tables");
		Thread.sleep(3000);
		login.typeAheadWebElement("Target Table", "automation_transform_dev");
		login.clickSpanText("Proceed");
		login.waitForPageLoad(v2.getPipelineNode("Target_Operation - automation_transform_dev"));
		v2.connectSourceTarget("drop_duplicates", "Target_Operation - automation_transform_dev");
		v2.clickSpanText("Save");
		login.isObjectExist(v2.pipelinesaved);
		login.doubleClick(v2.getPipelineNode("Target_Operation - automation_transform_dev"), "Target_Operation - automation_transform_dev");
		login.isDialogHeaderPresent("h2", "Target Configuration: Target_Operation");
		login.textClick("div", "Column Mapping");
		login.clickSpanText("Auto Map");
		v2.targetConfigurationCloseButton();
		v2.clickSpanText("Save");
		login.clickSpanText("Deploy");
		login.isObjectExist(v2.deployMessage);
		v2.searchbox(TranformationPipelineName);
		login.isDataPresentInColumn("Current Version", "Version 2");
		v2.clickVersionHistory();
		v2.isDialogHeaderPresent("h4", "Version History");
		v2.clickCheckBox("Version 2");
		v2.clickCheckBox("Base Version");
		v2.clickSpanText("Compare");
		v2.isDialogHeaderPresent("h4", "Compare");
		v2.clickSpanText("All Lines");
		v2.dialogCloseButton("h4", "Compare");
		v2.searchbox(TranformationPipelineName);
		login.clickEdit();
		v2.clickSpanText("Preview Structure");
		v2.isDialogHeaderPresent("div", "Pipeline Script");
		v2.pipelineScriptVerification("FROM Lakehouse_Datalake_Analytics_Dev.customertestscd2");
		login.clickDownloadButton();
		v2.downloadFile(v2.filesFolderPath+"PipelineScriptPythonFile.py");
		v2.clickSpanText("Close");
		v2.selectFromVersionDropdown("Base Version");
		v2.isObjectExist(v2.getPipelineNode("customertargetdim"));
		v2.clickViewVersionHistory();
		v2.isDialogHeaderPresent("h4", "Version History");
		v2.dialogCloseButton("h4", "Version History");
		
	}
	@Test(priority=7)
	public void dataNexusdataModel() throws InterruptedException, IOException {
		DataNexusDataModel model = new DataNexusDataModel(getDriver());
		checkRunFlag("DataNexusdataModel");
		login.clickSideNavigationModule("Data Model");
		login.isHeaderPresent("h5", "Data Model");
		model.clickAddDataModelButton();
		login.isHeaderPresent("div", "Create Data Model");
		model.enterDataModelName(model.modelName);
		model.enterDataModelDescription("Data Model For Automation Testing");
		login.clickSpanText("Submit");
		login.isObjectExist(model.createdDataModelMsg);
		//login.isTextPresentInColumn("Name", model.modelName);
		login.isTextPresentInColumn("Description", "Data Model For Automation Testing");
		login.isTextPresentInColumn("Created Date", login.todayDate);
		login.clickEdit();
		login.isDialogHeaderPresent("div", "Edit Data Model");
		model.enterDataModelDescription("Data Model For Automation Testing updated");
		login.clickSpanText("Update");
		login.isObjectExist(model.updatedDataModelMsg);
		login.isTextPresentInColumn("Description", "Data Model For Automation Testing updated");
		model.clickAddDataModelButton();
		login.isHeaderPresent("div", "Create Data Model");
		model.enterDataModelName(model.modelName);
		model.enterDataModelDescription("Data Model For Automation Testing");
		login.clickSpanText("Submit");
		login.isObjectExist(model.duplicateDataModelMsg);
		login.clickCancel();
		login.clickViewButton();
		//login.isHeaderPresent("span", model.modelName);
		model.clickAddTablesButton();
		login.isDialogHeaderPresent("h4", "Add New Table");
		login.clickSpanText("Save");
		login.isObjectExist(model.mandatoryDisplayNameMsg);
		model.enterDisplayName("testuser1");
		model.enterTableDescription("Automation test table");
		login.clickSpanText("Save");
		login.isObjectExist(model.mandatoryColumnNameMsg);
		model.enterColumnName("id");
		login.clickSpanText("Save");
		login.isObjectExist(model.mandatoryDataTypeMsg);
		model.selectDataType("Integer");
		model.primaryKeyCheckbox.click();
		login.clickSpanText("Take Action");
		login.isObjectExist(model.mandatorySelectColumnMsg);
		model.columnSelectCheckbox.click();	
		login.clickSpanText("Take Action");
		login.textClick("div", "Add to Group");
		//login.isDialogHeaderPresent("div", "Add to Group");	
		model.addGroupSelectGroup("Basic Info");
		model.clickAddToGroupCloseIcon();
		model.clickAddColumnButton();
		login.clickSpanText("String");
		model.tableAddColumnValue("Name");
		model.clickAddColumnButton();
		model.clickDeleteButton("2");
		login.clickSpanText("Save");
		login.isObjectExist(model.tableCreatedMsg);
		//login.isTextPresentInColumn("Name", "testuser1");
		//login.isTextPresentInColumn("Description", "Automation test table");
		//login.isValidDateFormat(model.fristCreatedDate.getText());
		login.clickEdit();
		login.isDialogHeaderPresent("h4", "Edit Table");
		model.enterTableDescription("Automation test table updated");
		login.clickSpanText("Save");
		login.isObjectExist(model.tableUpdatedMsg);
		//login.isTextPresentInColumn("Description", "Automation test table updated");
		login.clickDelete();
		login.clickYesButton();
		login.isObjectExist(model.tableDeleteMsg);
	}@Test(priority=6)
	public void DataNexusOrchestrator() throws InterruptedException, IOException {
		DataNexusOrchestrator orch = new DataNexusOrchestrator(getDriver());
		DataNexusIngestionPipeline igp = new DataNexusIngestionPipeline(getDriver());
		checkRunFlag("DataNexusOrchestrator");
		login.clickSideNavigationModule("Orchestrator");
		login.isHeaderPresent("h5", "Process Scheduler");
		orch.clickNewProcessButton();
		orch.enterPipelineName(OrchestratorName);
		orch.enterPipelineDescription("Automation Testing");
		orch.clickAddPipelineButton();
		orch.selectPipelineType("Ingestion");
		orch.selectPipeline(IngestionPipelineName);
		orch.clickSpanText("Done");
		orch.clickAddPipelineButton();
		orch.selectPipelineType("Transformation");
		orch.selectPipeline("Test1234567");
		orch.selectPipelineDependentUpon(IngestionPipelineName);
		orch.clickSpanText("Done");
		orch.clickSpanText("Save");
		login.isObjectExist(orch.scheduleCreatedMsg);
		login.enterInSearchbox(OrchestratorName);
		login.textClick("div", OrchestratorName);
		orch.clickProcessPipeline(IngestionPipelineName);
		login.isHeaderPresent("h2", "View Pipeline");
		login.clickClose();
		login.textClick("a", "Process");
		//login.clickYesButton();
		login.enterInSearchbox(OrchestratorName);
		login.clickEdit();
		orch.clickAddedPipelineDeleteButton(IngestionPipelineName);
		login.clickSpanText("Update");
		login.isObjectExist(orch.processUpdatedMsg);
		login.enterInSearchbox(OrchestratorName);
		orch.isTextPresentInColumnOrchestrator("Process Name", OrchestratorName);
		login.clickTrigger();
		login.clickYesButton();
		login.isObjectExist(orch.pipelineTriggeredMessage);
		login.clickViewLogsButton();
		login.isHeaderPresent("span", "Process Scheduler Logs");
		login.enterInSearchbox("Manual");
		orch.clickProcessId();
		orch.waitForProcessCompleted();
		login.getPipelineStatus();
		login.clickSpanText("Process Scheduler Logs");
		login.enterInSearchbox(OrchestratorName);
		login.clickScheduleButton();
		login.isDialogHeaderPresent("div", "Schedule Pipeline");
		login.clickSpanText("Save & Close");
		login.isObjectExist(orch.mandatoryTriggerDate);
		login.isObjectExist(orch.mandatoryTriggerTime);
		login.setTriggerDate();
		login.setTriggerTime(-2);
		login.isObjectExist(orch.pastTimeErrorMsg);
		login.setTriggerTime(2);
		login.setFocusOn(login.triggerDate);
		login.clickSpanText("Save & Close");
		login.isObjectExist(login.scheduleUpdatedMsg);
		login.clickViewSchedule();
		login.isObjectExist(orch.scheduleID);
		login.setFocusOn(orch.scheduleID);
		orch.clickScheduleCloseButton();
		login.enterInSearchbox(OrchestratorName);
		login.clickViewLogsButton();
		login.enterInSearchbox("Scheduled");
		orch.clickProcessId();
		orch.waitForProcessCompleted();
		login.getPipelineStatus();
		login.clickSpanText("Process Scheduler Logs");
		login.enterInSearchbox(OrchestratorName);
		orch.clickDeactivatePipelineButton();
		login.clickYesButton();
		orch.isObjectExist(orch.pipelineDeativatedMsg);
		login.enterInSearchbox(OrchestratorName);
		orch.clickActivatePipelineButton();
		login.clickYesButton();
		login.isObjectExist(orch.pipelineDeacticatedMessage);
		login.enterInSearchbox(OrchestratorName);
		login.clickViewSchedule();
		login.clickSpanText("Edit Schedules");
		login.isDialogHeaderPresent("div", "Schedule Pipeline");
		orch.clickScheduleCloseButton();
		login.enterInSearchbox(OrchestratorName);
		login.clickDelete();
		login.clickYesButton();
		login.isObjectExist(orch.pipelineDeletedMessage);
		
	}@Test(priority = 8)
	public void DataNexusDataProfiler() throws InterruptedException, IOException{
		checkRunFlag("DataNexusDataProfiler");
		
	}@Test(priority =9)
	public void DataNexusMonitoring() throws InterruptedException, IOException{
		checkRunFlag("DataNexusMonitoring");
		DataNexusMonitoring monitor = new DataNexusMonitoring(getDriver());
		login.clickSideNavigationModule("Monitoring");
		login.isHeaderPresent("h5", "Monitoring");
		login.enterInSearchbox(IngestionPipelineName);
		login.isTextPresentInColumn("Pipeline Name", IngestionPipelineName);
		login.isTextPresentInColumn("Source Connection Name", ConnectionName);
		login.clickSortingButton("Pipeline Name");	
		login.sortingValidation("Pipeline Name", "Ascending");
		login.clickTrigger();
		login.isHeaderPresent("span", IngestionPipelineName);
		login.enterInSearchbox(monitor.getColumnData("Log Id"));
		login.clickSortingButton("Lod Id");
		login.sortingValidation("Log Id", "Ascending");
		monitor.clickcolumnData("Log Id");
		login.textClick("div", "Transformation And Data Quality");
		login.enterInSearchbox(TranformationPipelineName);	
		login.isHeaderPresent("span", "Successfull");
		login.isTextPresentInColumnDiv("Operation Name", "Target");
		login.isTextPresentInColumnTable("Operation Type", "overwrite_delta_table");
		login.isTextPresentInColumnTable("Operation Name", "Target");
		
		
		
	}@Test(priority=10)
	public void DataNexusTenants() throws InterruptedException, IOException{
		checkRunFlag("DataNexusMonitoring");
		login.clickSideNavigationModule("Admin");
		login.clickSideNavigationModule("Tenants");
	}
}
