package testCases;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;

import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.UnexpectedTagNameException;
import org.testng.Assert;
import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;

import pageObjects.DataNexusDataDictionary;
import pageObjects.DataNexusDataModel;
import pageObjects.DataNexusDataProfiler;
import pageObjects.DataNexusIngestionPipeline;
import pageObjects.DataNexusOrchestrator;
import pageObjects.DataNexusTransformationPipeline;
import pageObjects.DataNexusUserManagement;
import pageObjects.MDMEntities;
import pageObjects.MDMIntegrationPipeline;
import pageObjects.MDMOverview;
import pageObjects.UserManagement;
import pageObjects.dataNexusDataLake;
import pageObjects.dataNexusHome;
import pageObjects.landingPage;
import pageObjects.loginPage;
import pageObjects.workspaceList;
import testBase.baseClass;
public class sanityTesting extends baseClass{
	loginPage login;
	workspaceList ws;
	dataNexusHome home ;
	@Test(priority=1)
	public void loginPage() throws InterruptedException,UnexpectedTagNameException, IOException{
		login = new loginPage(driver);
		FileReader file = new FileReader("./src//test//resources//config.properties");
		p=new Properties();
		p.load(file);
		login.enterUsername(p.getProperty("username"));
		login.enterPassword(p.getProperty("password"));
		login.clickLogin();
		String successLoginMessage=login.getLoginMessage();
		Thread.sleep(2000);
		login.compareStrings(successLoginMessage, "Logged In Successfully.","Successful Login message");
	}@Test(priority=2)
	public void landingPage() throws InterruptedException,UnexpectedTagNameException, IOException{
		landingPage landing = new landingPage(driver);
		login.isObjectExist(landing.dataSolutions);
		landing.dataNexusClick();
	}
	@Test(priority=3)
	public void workspaceListDataNexus() throws InterruptedException,UnexpectedTagNameException, IOException{
		ws = new workspaceList(driver);
		login.isObjectExist(ws.onePlatformLogoWorkspaceListPage);
		login.isHeaderPresent("h1", "Workspaces");
		ws.clickMDMButton();
		login.isObjectExist(ws.firstMDMWorkspace);
		ws.clickPAIButton();
		login.isObjectExist(ws.firstPAIWorkspace);
		ws.clickDataNexus();
		String secondWorkspace = login.getText(ws.secondWorkspace);
		ws.searchBox(secondWorkspace);
		Thread.sleep(1000);
		ws.clickWorkSpace();
	}
	@Test(priority=4)
	public void dataNexus() throws InterruptedException,UnexpectedTagNameException, IOException{
		home= new dataNexusHome(driver);
		login.extendedWait.until(ExpectedConditions.visibilityOf(home.totalPipelines));
		login.isHeaderPresent("h5", "Home");
		home.searchBox(home.firstPipeline.getText());
		login.isObjectExist(home.firstPipeline);
		home.clickActive();
		home.clickInctive();
		home.clickScheduled();
		dataNexusDataLake dataLake = new dataNexusDataLake(driver);
		dataLake.clickDataLake();
		login.isHeaderPresent("h5", "Data Lake");
		login.wait.until(ExpectedConditions.elementToBeClickable(dataLake.treeSwitch));
		//login.dropdownElement(dataLake.lakeHouseSelectDropdown, dataLake.);
		//Select select = new Select(dataLake.lakeHouseSelectDropdown);
		//select.selectByVisibleText("Silver_LH");
		login.isHeaderPresent("h3", "Directory Structure");
		dataLake.addRootDirectory();
		dataLake.driectoryName("Testing");
		login.clickCancel();
		dataLake.clickTable();
		//login.wait.until(ExpectedConditions.elementToBeClickable(dataLake.treeSwitch));
		login.isHeaderPresent("h6", "Tables");
		login.clickSideNavigationModule("Connections");
		login.isHeaderPresent("h5","Connections");
		login.clickCreateNew();
		login.isHeaderPresent("span", "New Connection");
		login.clickClose();
		login.clickSideNavigationModule("Ingestion Pipeline");
		login.isHeaderPresent("h5","Ingestion Pipelines");
		login.clickCreateNew();
		DataNexusIngestionPipeline ig = new DataNexusIngestionPipeline(driver);
		ig.enterPipelineName(ig.iGPipelineName);
		ig.selectLakehouseName("Silver_LH");
		ig.selectDatalkeName("BDS_SAMPLE_DATA");
		ig.selectSource("Test_sql_server");
		ig.selectSchema("HumanResources");
		login.clickCancel();
		login.clickSideNavigationModule("Transformation Pipeline");
		login.isHeaderPresent("h5","Transformation Pipeline");
		login.clickCreateNew();
		DataNexusTransformationPipeline ts = new DataNexusTransformationPipeline(driver);
		login.mouseOverElement(ts.addSource);
		login.clickSpanText("Delta Lake");
		login.isHeaderPresent("div", "Select Data Lake");
		ts.standardDropdownElement("Select Lake House","Lakehouse_Datalake_Analytics_Dev.Lakehouse");
		ts.standardDropdownElement("Select Lake House Type","Tables");
		ts.selectDataLakeCloseIcon.click();
		login.clickSideNavigationModule("Data Model");
		DataNexusDataModel datamodel = new DataNexusDataModel(driver);
		login.isHeaderPresent("h5","Data Model");
		login.standardClickButton(datamodel.addDataModel,"Add Data Model");
		login.isHeaderPresent("div","Create Data Model");
		datamodel.standardEnterTextbox(datamodel.dataModelName, datamodel.modelName, "Data Model Name");
		datamodel.standardEnterTextbox(datamodel.dataModelDescription, "Testing1234", "Description");
		login.clickCancel();
		/*login.clickSideNavigationModule("Data Dictionary");
		login.isHeaderPresent("h5","Data Dictionary");
		DataNexusDataDictionary dict = new DataNexusDataDictionary(driver);
		dict.standardClickButton(dict.silverLayer, "Silver Layer");
		dict.standardClickButton(dict.goldLayer, "Gold Layer");*/
		login.clickSideNavigationModule("Orchestrator");
		login.isHeaderPresent("h5","Process Scheduler");	
		DataNexusOrchestrator orch = new DataNexusOrchestrator(driver);
		login.standardClickButton(orch.createNewProcessButton, "Create New Process");
		//login.nonLinkText("New Process");
		login.clickSideNavigationModule("Data Profiler");
		login.isHeaderPresent("h5","Data Profiler");
		DataNexusDataProfiler dataprofile = new DataNexusDataProfiler(driver);
		login.isObjectExist(dataprofile.lakehouseDataFecthedMessage);
		login.dropdownElement(dataprofile.dataLakeHouse, "Lakehouse_Datalake_Analytics_Dev","Date LakeHouse");
		login.dropdownElement(dataprofile.selectTable,"Config_Logs_Transformation","Table");
		login.isObjectExist(dataprofile.profileDataFecthedMessage);
		login.clickSideNavigationModule("Monitoring");
		login.isHeaderPresent("h5","Monitoring");
		//login.isObjectExist(login.logsIcon);
		login.clickSideNavigationModule("Admin");
		login.clickSideNavigationModule("Tenants");
		login.isHeaderPresent("h5","Tenants");
		login.clickSpanText("Add Tenant");
		login.isHeaderPresent("h4","Add New Tenant");
		login.clickClose();
		login.clickSideNavigationModule("Lineage");
		login.clickSideNavigationModule("Admin");
		login.clickSideNavigationModule("User Management");
		DataNexusUserManagement usermanage = new DataNexusUserManagement(driver);
		login.isHeaderPresent("h5","User Management");
		login.clickSpanText("New Role");
		login.nonLinkText("New Role");
		login.clickLinkText("User Management");
		login.standardClickButton(usermanage.usersTab, "Users");
		login.clickSpanText("New User");
		login.nonLinkText("Add User");
		login.topNavigationSection("Profile");
		login.isHeaderPresent("h5","My Info");
		/*login.topNavigationSection("Log out");
		login.isObjectExist(login.logoutUserMsg);
		login.isObjectExist(login.username_textbox);*/
		
	}@Test(priority=5)
	public void workspaceListMDM() throws InterruptedException,UnexpectedTagNameException, IOException{
		login.checkAndNavigateWorkspaceListPage();
		ws.clickMDMButton();
		ws.searchBox("MDM Workspace");
		Thread.sleep(1000);
		ws.clickWorkSpace();
	}@Test(priority=6)
	public void MDM_Sanity() throws InterruptedException,UnexpectedTagNameException, IOException{
		MDMOverview overview = new MDMOverview(driver);
		home= new dataNexusHome(driver);
		//home= new dataNexusHome(driver);
		login.isHeaderPresent("h5", "Home");
		login.isObjectExist(overview.mDMHomeRecordIcon("Total Records"));
		login.isObjectExist(overview.mDMHomeRecordIcon("Unique Clean Records"));
		login.isObjectExist(overview.mDMHomeRecordIcon("Total Entities"));
		login.isObjectExist(overview.mDMHomeRecordIcon("Potential Duplicate %"));
		login.isObjectExist(overview.mDMHomeRecordIcon("Incomplete Records %"));
		overview.clickpotentialDuplicateViewDetail();
		login.isHeaderPresent("span", "Potential Duplicate Records");
		login.clickSpanText("Dashboard");
		overview.clickincompleteRecordsViewDetail();
		login.isHeaderPresent("span", "Incomplete Record Table");
		login.clickSpanText("Dashboard");
		login.clickSideNavigationModule("Entities");
		MDMEntities entities = new MDMEntities(driver);
		entities.clickFirstSideNavEntity();
		login.isHeaderPresent("h5", "Entity");
		login.clickSpanText("Add New");
		login.isHeaderPresent("h2", "New Parent");
		login.clickClose();
		login.clickYesButton();
		entities.clickEntityCard();
		entities.clickEntityCard();
		entities.clickEntityCard();
		entities.clickEntityCard();
		entities.clickEntityCard();
		login.isHeaderPresent("span", "Golden Record Details");
		login.clickBackButton();
		//login.enterInSearchbox("10");
		//login.compareStrings("10", entities.entityCard.getText(), "Card ");
		login.clickSideNavigationModule("Taxonomy");
		login.isHeaderPresent("h5", "Taxonomy");
		login.clickSpanText("Add New");
		login.isHeaderPresent("span", "Add New Taxonomy");
		//entities.selectCreatedTaxonomyFor("Sample Data");
		entities.enterTaxonomyName("Taxonomy123");
		login.clickSideNavigationModule("Masters");
		login.isHeaderPresent("h5", "Masters");
		login.waitForPageLoad(login.searchbox);
		login.clickSpanText("Add Master");
		login.isHeaderPresent("span", "New Master");
		login.textClick("div", "Masters");
		login.clickYesButton();
		//login.enterInSearchbox(login.columnTextLink("Name").getText());
		//login.clearTextbox(login.searchbox);
		//login.enterInSearchbox(login.columnTextLink("Name").getText());
		String s = login.columnTextLink("Name").getText();
		login.columnTextLink("Name").click();
		login.waitForPageLoad(login.columnTextLink("id"));
		login.clickSpanText("Data Entry");
		login.isHeaderPresent("span", s);
		login.clickSideNavigationModule("Integration");
		login.clickSideNavigationModule("Connectors");
		login.isHeaderPresent("h6", "Data Sources");
		login.clickSpanText("Add New");
		login.isHeaderPresent("h2", "New Connection");	
		login.clickSideNavigationModule("Pipelines");
		login.waitForPageLoad(home.totalPipelines);
		login.clickSpanText("New Pipeline");
		login.isHeaderPresent("div", "Choose Transformation Type");
		MDMIntegrationPipeline pipeline = new MDMIntegrationPipeline(driver);
		pipeline.clickTransformationTypeDialogCloseButton();
		login.enterInSearchbox(pipeline.firstPipelineName.getText());
		pipeline.clickEditPipeline();
		login.textClick("a", "Pipelines");
		login.clickYesButton();
		login.enterInSearchbox(pipeline.firstPipelineName.getText());
		pipeline.clickViewPipeline();
		login.textClick("a", "Pipelines");
		//login.clickYesButton();
		login.enterInSearchbox(pipeline.firstPipelineName.getText());
		pipeline.clickScheculedPipeline();
		login.isHeaderPresent("div", "Schedule Pipeline");
		pipeline.schedulePipelineDialogCloseButton();
		login.clickSideNavigationModule("Data Quality");
		login.isHeaderPresent("h5", "Data Quality Dashboard");
		login.isObjectExist(overview.mDMHomeRecordIcon("Total Records"));
		login.isObjectExist(overview.mDMHomeRecordIcon("Unique Clean Records"));
		login.isObjectExist(overview.mDMHomeRecordIcon("Total Entities"));
		login.isObjectExist(overview.mDMHomeRecordIcon("Potential Duplicate %"));
		login.isObjectExist(overview.mDMHomeRecordIcon("Incomplete Records %"));
		overview.clickpotentialDuplicateViewDetail();
		login.isHeaderPresent("span", "Potential Duplicate Records");
		login.enterInSearchbox("Product");
		overview.clickViewTableButton();
		login.isHeaderPresent("span","Product Report");
		login.clickSpanText("Dashboard");
		login.clickSpanText("Dashboard");
		overview.clickincompleteRecordsViewDetail();
		login.isHeaderPresent("span", "Incomplete Record Table");
		login.enterInSearchbox("Student");
		overview.clickViewTableButton();
		login.isHeaderPresent("span", "Student");
		login.textClick("a", "Incomplete Records Table");
		login.clickSpanText("Dashboard");
		login.clickSideNavigationModule("Settings");
		login.clickSideNavigationModule("Audit Logs");
		login.isHeaderPresent("h5", "Audit Logs");
		login.clickSideNavigationModule("User Management");
		login.isHeaderPresent("h5", "User Management");
		login.clickSpanText("New Role");
		UserManagement user = new UserManagement(driver);
		login.textClick("a", "User Management");
		String roleName=user.firstRoleName.getText();
		login.enterInSearchbox(roleName);
		login.textClick("p", roleName);
		login.textClick("a", "User Management");
		login.enterInSearchbox(roleName);
		login.clickEdit();
		login.textClick("a", "User Management");
		login.topNavigationSection("Log out");
		login.isObjectExist(login.logoutUserMsg);
		login.isObjectExist(login.username_textbox,"Login textbox");
	}
}
